spring.application.name=project-management

# PostgreSQL config
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/project_management}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.resources.add-mappings=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework=INFO

# GROQ API config
groq.api.key=${GROQ_API_KEY:}
groq.api.base=${GROQ_API_BASE:https://api.groq.com/openai/v1}
